from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol, Self
from uuid import UUID

from packages.core.domain.models import (
    Agent,
    AgentStatus,
    CandidateLifecycle,
    CandidateState,
    CriticFinding,
    CrossPollinationPacket,
    EngineeringArtifact,
    EngineeringCheck,
    EngineeringRun,
    EngineeringStage,
    EngineeringStatus,
    Evaluation,
    Generation,
    Job,
    JobType,
    KnowledgeItem,
    LineageLink,
    ModelCall,
    ModelProfile,
    ModelState,
    Problem,
    Project,
    Run,
    RunEvent,
    RunStatus,
    SelectionDecision,
    Submission,
    VerificationResult,
)


class EngineeringRunRepository(Protocol):
    def add(self, run: EngineeringRun) -> EngineeringRun: ...
    def get(self, engineering_run_id: UUID) -> EngineeringRun | None: ...
    def list_all(self) -> list[EngineeringRun]: ...
    def update_status(
        self,
        engineering_run_id: UUID,
        status: EngineeringStatus,
    ) -> EngineeringRun: ...
    def increment_repair(self, engineering_run_id: UUID) -> EngineeringRun: ...


class EngineeringArtifactRepository(Protocol):
    def add(self, artifact: EngineeringArtifact) -> EngineeringArtifact: ...
    def list_for_run(self, engineering_run_id: UUID) -> list[EngineeringArtifact]: ...
    def list_for_stage(
        self,
        engineering_run_id: UUID,
        stage: EngineeringStage,
        repair_cycle: int | None = None,
    ) -> list[EngineeringArtifact]: ...


class EngineeringCheckRepository(Protocol):
    def add_many(self, checks: Iterable[EngineeringCheck]) -> list[EngineeringCheck]: ...
    def list_for_run(self, engineering_run_id: UUID) -> list[EngineeringCheck]: ...
    def list_for_cycle(
        self,
        engineering_run_id: UUID,
        repair_cycle: int,
    ) -> list[EngineeringCheck]: ...


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: UUID) -> Project | None: ...
    def list_all(self) -> list[Project]: ...


class ProblemRepository(Protocol):
    def add(self, problem: Problem) -> Problem: ...
    def get(self, problem_id: UUID) -> Problem | None: ...


class RunRepository(Protocol):
    def add(self, run: Run) -> Run: ...
    def get(self, run_id: UUID) -> Run | None: ...
    def list_all(self) -> list[Run]: ...
    def update_status(self, run_id: UUID, status: RunStatus) -> Run: ...


class GenerationRepository(Protocol):
    def add(self, generation: Generation) -> Generation: ...
    def get(self, generation_id: UUID) -> Generation | None: ...
    def get_for_run(self, run_id: UUID, index: int) -> Generation | None: ...
    def list_for_run(self, run_id: UUID) -> list[Generation]: ...


class AgentRepository(Protocol):
    def add_many(self, agents: Iterable[Agent]) -> list[Agent]: ...
    def get(self, agent_id: UUID) -> Agent | None: ...
    def list_for_generation(self, generation_id: UUID) -> list[Agent]: ...
    def update_status(self, agent_id: UUID, status: AgentStatus) -> Agent: ...


class SubmissionRepository(Protocol):
    def add(self, submission: Submission) -> Submission: ...
    def get(self, submission_id: UUID) -> Submission | None: ...
    def get_for_agent(self, agent_id: UUID) -> Submission | None: ...
    def list_for_generation(self, generation_id: UUID) -> list[Submission]: ...


class EvaluationRepository(Protocol):
    def add(self, evaluation: Evaluation) -> Evaluation: ...
    def list_for_submission(self, submission_id: UUID) -> list[Evaluation]: ...
    def list_for_generation(self, generation_id: UUID) -> list[Evaluation]: ...


class SelectionRepository(Protocol):
    def add_many(self, decisions: Iterable[SelectionDecision]) -> list[SelectionDecision]: ...
    def list_for_generation(self, generation_id: UUID) -> list[SelectionDecision]: ...


class LineageRepository(Protocol):
    def add_many(self, links: Iterable[LineageLink]) -> list[LineageLink]: ...
    def get_for_child(self, child_agent_id: UUID) -> LineageLink | None: ...
    def list_for_generation(self, generation_id: UUID) -> list[LineageLink]: ...


class CandidateStateRepository(Protocol):
    def add_many(self, states: Iterable[CandidateState]) -> list[CandidateState]: ...
    def get_for_submission(self, submission_id: UUID) -> CandidateState | None: ...
    def list_for_generation(self, generation_id: UUID) -> list[CandidateState]: ...
    def update_status(
        self,
        submission_id: UUID,
        status: CandidateLifecycle,
    ) -> CandidateState: ...


class CriticFindingRepository(Protocol):
    def add(self, finding: CriticFinding) -> CriticFinding: ...
    def get_for_agent_submission(
        self,
        critic_agent_id: UUID,
        submission_id: UUID,
    ) -> CriticFinding | None: ...
    def list_for_generation(self, generation_id: UUID) -> list[CriticFinding]: ...


class CrossPollinationRepository(Protocol):
    def add_many(
        self,
        packets: Iterable[CrossPollinationPacket],
    ) -> list[CrossPollinationPacket]: ...
    def list_for_agent(self, agent_id: UUID) -> list[CrossPollinationPacket]: ...
    def list_for_generation(self, generation_id: UUID) -> list[CrossPollinationPacket]: ...


class KnowledgeRepository(Protocol):
    def add_many(self, items: Iterable[KnowledgeItem]) -> list[KnowledgeItem]: ...
    def list_for_run(self, run_id: UUID) -> list[KnowledgeItem]: ...
    def list_for_generation(self, generation_id: UUID) -> list[KnowledgeItem]: ...


class VerificationRepository(Protocol):
    def add_many(self, results: Iterable[VerificationResult]) -> list[VerificationResult]: ...
    def list_for_submission(self, submission_id: UUID) -> list[VerificationResult]: ...
    def list_for_generation(self, generation_id: UUID) -> list[VerificationResult]: ...


class ModelProfileRepository(Protocol):
    def add(self, profile: ModelProfile) -> ModelProfile: ...
    def get(self, profile_id: UUID) -> ModelProfile | None: ...
    def find(self, provider: str, model: str) -> ModelProfile | None: ...


class ModelStateRepository(Protocol):
    def add(self, state: ModelState) -> ModelState: ...
    def get_for_profile(self, model_profile_id: UUID) -> ModelState | None: ...
    def list_all(self) -> list[ModelState]: ...
    def observe_call(
        self,
        model_profile_id: UUID,
        *,
        success: bool,
        latency_ms: int | None,
    ) -> ModelState | None: ...


class ModelCallRepository(Protocol):
    def add(self, call: ModelCall) -> ModelCall: ...
    def get(self, call_id: UUID) -> ModelCall | None: ...
    def list_for_run(self, run_id: UUID) -> list[ModelCall]: ...


class RunEventRepository(Protocol):
    def append(self, event: RunEvent) -> RunEvent: ...
    def list_for_run(self, run_id: UUID, after_id: UUID | None = None) -> list[RunEvent]: ...


class JobQueue(Protocol):
    def enqueue(
        self,
        job_type: JobType,
        payload: dict[str, Any],
        idempotency_key: str,
        max_attempts: int = 3,
    ) -> Job: ...


class UnitOfWork(Protocol):
    engineering_runs: EngineeringRunRepository
    engineering_artifacts: EngineeringArtifactRepository
    engineering_checks: EngineeringCheckRepository
    projects: ProjectRepository
    problems: ProblemRepository
    runs: RunRepository
    generations: GenerationRepository
    agents: AgentRepository
    submissions: SubmissionRepository
    evaluations: EvaluationRepository
    selections: SelectionRepository
    lineages: LineageRepository
    candidate_states: CandidateStateRepository
    critic_findings: CriticFindingRepository
    cross_pollination: CrossPollinationRepository
    knowledge: KnowledgeRepository
    verifications: VerificationRepository
    model_profiles: ModelProfileRepository
    model_states: ModelStateRepository
    model_calls: ModelCallRepository
    events: RunEventRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
