FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml alembic.ini ./
COPY packages ./packages
COPY services ./services

RUN python -m pip install --no-cache-dir .

CMD ["python", "-m", "services.worker.worker.main"]
