from __future__ import annotations

import json
from collections import deque

from packages.providers.base import ModelRequest, ModelResponse


class FakeProvider:
    """Deterministic scripted provider for unit tests."""

    def __init__(self, responses: list[str] | None = None) -> None:
        self._responses = deque(responses or [])

    async def generate(self, request: ModelRequest) -> ModelResponse:
        text = self._responses.popleft() if self._responses else "{}"
        return ModelResponse(
            text=text,
            provider="fake",
            model=request.model_profile,
            latency_ms=0,
            estimated_cost=0.0,
        )


class PhaseOneFakeProvider:
    """Schema-valid fake provider used by the runnable local Phase 1 stack."""

    async def generate(self, request: ModelRequest) -> ModelResponse:
        if request.task_type == "research":
            text = json.dumps(
                {
                    "summary": "Deterministic local research candidate",
                    "approach": "Analyze the supplied problem independently.",
                    "claims": [
                        {
                            "statement": "This is a synthetic Phase 1 claim.",
                            "confidence": 0.75,
                            "support": "Generated by the deterministic fake provider.",
                        }
                    ],
                    "evidence": ["synthetic local evidence"],
                    "discoveries": ["the orchestration path is operational"],
                    "failed_attempts": [],
                    "open_questions": [],
                    "final_answer": "Synthetic answer for local orchestration validation.",
                }
            )
        elif request.task_type == "judge":
            candidate_ids = request.metadata.get("candidate_ids") or []
            text = json.dumps(
                {
                    "evaluations": [
                        {
                            "candidate_id": candidate_id,
                            "correctness": 0.8,
                            "rigor": 0.8,
                            "novelty": 0.5,
                            "research_progress": 0.7,
                            "verifiability": 0.9,
                            "fatal_error": False,
                            "judge_confidence": 0.85,
                            "critique": "Deterministic local blind evaluation.",
                        }
                        for candidate_id in candidate_ids
                    ]
                }
            )
        else:
            raise ValueError(f"Unsupported fake task type: {request.task_type}")

        return ModelResponse(
            text=text,
            provider="fake",
            model=request.model_profile,
            latency_ms=0,
            input_tokens=0,
            output_tokens=0,
            estimated_cost=0.0,
        )
